### ISSUE TITLE
Need License

### ISSUE THREAD

**Issue by chris-short** [guilhem/rss-issues-action#14]
Hello!

As a member of the Kubernetes Upstream Marketing team, we would love to use this GitHub Action to create issues for us in our repo. But, there needs to be a license. Would you be willing to open source this project under [MIT](https://mit-license.org/) or [Apache 2](https://www.apache.org/licenses/LICENSE-2.0.html) Licenses?

Doc: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by guilhem** [comment]
Hi @chris-short,
I always put all my work in Apache2, let's go for it ;)
