### ISSUE TITLE
notify user

### ISSUE THREAD

**Issue by pared** [guilhem/rss-issues-action#2]
add assignees/notify field so that it is possible to ping a particular user(s)

**Comment by guilhem** [comment]
Good Idea :)
But I think I will create another action for this purpose: assign an issue if it has a specific label

You may use this one https://github.com/marketplace/actions/issue-auto-labeling-and-assigning with a match on prefix.

**Comment by pared** [comment]
Thank you @guilhem!
> But I think I will create another action for this purpose: assign an issue if it has a specific label

so, should I close this one?
